#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
#xrandr --setprovideroutputsource 
#modesetting NVIDIA-0
xrandr --output eDP-1 --mode 1920x1080 --rate 60
#xrandr --output eDP-1 --mode 1920x1080 --rate 144 
#xrandr --output DP-1-0 --mode 1920x1080 --rate 144 --primary
#bspc monitor eDP-1 -d 1 2 3 4
bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor DP-1-0 -d 1 2 3 4
#bspc monitor eDP-1 -d 5 6 7

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
pipewire &
pipewire-pulse &
wireplumber &
#picom --config ~/.config/picom/picom.conf &
feh --bg-scale ~/Wallpapers/wallpaper5.jpg --bg-scale ~/Wallpapers/wallpaper5.jpg &
#feh --bg-scale ~/Wallpapers/wallpaper5.jpg &
dunst &
polybar &
